[mgr]
sort_by = "mtime"
sort_reverse = true
ratio = [0, 4, 3]
linemode = "size"

[opener]
edit = [
    { run = "nvim %s", block = true, for = "unix" }
]
browser = [
    { run = "xdg-open %s", orphan = true, desc = "Open in browser", for = "unix" },
]

[open]
prepend_rules = [
    { url = "*.html", use = "browser" },
    { url = "*.htm", use = "browser" }
]
